export type Ev = {
  date: string;
  title: string;
  kind: string;
  time?: string;
  venue: string;
  area: string;
  price?: string;
  url: string;
  note?: string;
};

export const EVENTS: Ev[] = [
  {
    date: "Mon 7 Sep",
    title: "Kaktüs Çiçeği",
    kind: "theatre",
    time: "21:00",
    venue: "Özgürlük Parkı Amfi Tiyatro",
    area: "Kadıköy",
    price: "from ₺528",
    url: "https://www.biletix.com/search/TURKIYE/tr?searchText=Kakt%C3%BCs%20%C3%87i%C3%A7e%C4%9Fi",
  },
  {
    date: "Mon 7 Sep",
    title: "The Invite / Davet",
    kind: "open-air cinema",
    time: "20:30",
    venue: "İstanbul Yelken Kulübü",
    area: "Fenerbahçe/Kadıköy",
    price: "₺514",
    url: "https://biletinial.com/tr-tr/etkinlik/the-invite-davet-acik-hava-gosterimi",
  },
  {
    date: "Tue 8 Sep",
    title: "Hadi Öldürsene Canikom",
    kind: "theatre",
    time: "21:00",
    venue: "Özgürlük Parkı",
    area: "Kadıköy",
    price: "from ₺1,120",
    url: "https://www.bubilet.com.tr/arama?q=Hadi%20%C3%96ld%C3%BCrsene%20Canikom",
  },
  {
    date: "Tue 8 Sep & Wed 9 Sep",
    title: "Kadıköy Açık Mikrofon Stand Up",
    kind: "stand-up",
    time: "20:15",
    venue: "Corner Kadıköy",
    area: "Kadıköy",
    url: "https://www.biletix.com/etkinlik/5ZENK/TURKIYE/tr/art-kadikoy-acik-mikrofon-stand-up-08-09-2026-istanbul",
    note: "Price unavailable.",
  },
  {
    date: "Tue 8 Sep",
    title: "Sil Baştan",
    kind: "open-air cinema",
    time: "20:30",
    venue: "İstanbul Yelken Kulübü",
    area: "Fenerbahçe/Kadıköy",
    price: "₺514",
    url: "https://biletinial.com/tr-tr/etkinlik/sil-bastan",
  },
  {
    date: "Tue 8 Sep",
    title: "Zengin Mutfağı",
    kind: "theatre",
    venue: "DasDas",
    area: "Ataşehir",
    url: "https://www.bubilet.com.tr/arama?q=Zengin%20Mutfa%C4%9F%C4%B1",
    note: "Time and price unavailable.",
  },
  {
    date: "Wed 9 Sep",
    title: "Mutlu Aile Tablosu",
    kind: "theatre",
    time: "21:00",
    venue: "Özgürlük Parkı",
    area: "Kadıköy",
    url: "https://www.bubilet.com.tr/arama?q=Mutlu%20Aile%20Tablosu",
    note: "Price unavailable.",
  },
  {
    date: "Thu 10 Sep",
    title: "Şairler Mezarlığı",
    kind: "theatre",
    time: "21:00",
    venue: "Özgürlük Parkı",
    area: "Kadıköy",
    url: "https://www.bubilet.com.tr/arama?q=%C5%9Eairler%20Mezarl%C4%B1%C4%9F%C4%B1",
    note: "Price unavailable.",
  },
  {
    date: "Thu 10 Sep",
    title: "Yürüyen Şato",
    kind: "open-air cinema",
    time: "20:30",
    venue: "İstanbul Yelken Kulübü",
    area: "Fenerbahçe/Kadıköy",
    price: "₺514",
    url: "https://biletinial.com/tr-tr/etkinlik/yuruyen-sato",
  },
  {
    date: "Thu 10 Sep",
    title: "Doğu Demirkol",
    kind: "stand-up",
    venue: "Sancaktepe Sahnesi",
    area: "Sancaktepe",
    url: "https://www.bubilet.com.tr/arama?q=Do%C4%9Fu%20Demirkol",
    note: "Time and price unavailable.",
  },
  {
    date: "Fri 11 Sep",
    title: "Kamufle",
    kind: "music",
    venue: "Muaf Kadıköy",
    area: "Kadıköy",
    url: "https://www.bubilet.com.tr/arama?q=Kamufle",
    note: "Time and price unavailable.",
  },
  {
    date: "Fri 11 Sep",
    title: "The Bodyguard",
    kind: "musical",
    time: "20:30",
    venue: "Zorlu PSM",
    area: "Beşiktaş",
    price: "₺5,500–₺7,500",
    url: "https://www.passo.com.tr/tr/etkinlik/bodyguard-muzikali-zorlupsm-turkcell-sahnesi-biletleri/11485326",
  },
  {
    date: "Sat 12 Sep",
    title: "Ayna",
    kind: "concert",
    time: "21:00",
    venue: "Özgürlük Parkı",
    area: "Kadıköy",
    price: "from ₺1,150",
    url: "https://www.biletix.com/search/TURKIYE/tr?searchText=Ayna",
  },
  {
    date: "Sat 12 Sep",
    title: "Maher Zain",
    kind: "concert",
    time: "21:00",
    venue: "Harbiye Açıkhava",
    area: "Şişli",
    price: "approx ₺1,230–₺1,400",
    url: "https://biletinial.com/tr-tr/muzik/maher-zain-konseri",
  },
  {
    date: "Sat 12 – Sun 13 Sep",
    title: "Rock’n Park İstanbul",
    kind: "festival",
    venue: "Life Park",
    area: "Sarıyer",
    price: "from approx ₺2,690",
    url: "https://www.biletix.com/search/TURKIYE/tr?searchText=Rock%27n%20Park%20%C4%B0stanbul",
  },
  {
    date: "Sat 12 Sep",
    title: "Ersay Üner",
    kind: "concert",
    venue: "Jolly Joker Vadistanbul",
    area: "Sarıyer",
    price: "from approx ₺3,940",
    url: "https://www.bubilet.com.tr/arama?q=Ersay%20%C3%9Cner",
    note: "Time unavailable.",
  },
  {
    date: "Sun 13 Sep",
    title: "Zülfü Livaneli & Maria Farantouri",
    kind: "concert",
    time: "21:00",
    venue: "Harbiye Açıkhava",
    area: "Şişli",
    url: "https://www.biletix.com/search/TURKIYE/tr?searchText=Z%C3%BClf%C3%BC%20Livaneli",
    note: "Price unavailable.",
  },
  {
    date: "Sat 12 – Sun 13 Sep",
    title: "İYK Sportsboat Türkiye Trophy",
    kind: "sailing",
    venue: "İstanbul Yelken Kulübü",
    area: "Fenerbahçe/Kadıköy",
    url: "https://www.iyk.org.tr/",
    note: "No spectator ticket.",
  },
  {
    date: "Mon 14 Sep",
    title: "Aşk ve Gurur",
    kind: "open-air cinema",
    time: "20:30",
    venue: "İstanbul Yelken Kulübü",
    area: "Fenerbahçe/Kadıköy",
    price: "₺514",
    url: "https://biletinial.com/tr-tr/etkinlik/ask-ve-gurur-film-gosterimi",
  },
];

export const CINEMAS = [
  {
    name: "Kadıköy Sineması",
    area: "Kadıköy",
    films: "Paris, Texas; En Sevdiğim Pastam; Birlikte; Dalga",
    url: "https://biletinial.com/tr-tr/mekan/kadikoy-sinemasi",
  },
  {
    name: "Paribu Cineverse Akasya",
    area: "Üsküdar",
    films: "Harry Potter ve Felsefe Taşı; Doraemon: Şeytanların Denizaltı Kalesi; Cebran; Sadece Bir Gece",
    url: "https://www.paribucineverse.com/filmler",
  },
];
